alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: admin.pujyapanditg.com
  type: PRIMARY
  zone: pujyapanditg.com
name: ppg-admin-frontend
region: blr
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: viveksharma8130/ppg_admin_frontend
  name: ppg-admin-frontend
  catchall_document: index.html
  routes:
  - path: /
  source_dir: /
